services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.12-management
    platform: linux/arm64/v8
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  ordersystem:
    build: .
    platform: linux/arm64/v8
    container_name: ordersystem
    restart: always
    ports:
      - "8000:8000"   # HTTP
      - "50051:50051" # gRPC
      - "8080:8080"   # GraphQL
    environment:
      GO_ENVIRONMENT: production
      # DB
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
      # servers
      WEB_SERVER_PORT: ":8000"
      GRPC_SERVER_PORT: "50051"
      GRAPHQL_SERVER_PORT: "8080"
      # RabbitMQ (IMPORTANTE)
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VHOST: /
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
